### ISSUE TITLE
[Steam Deck] - Video not streaming when display is turned off

### ISSUE THREAD

**Issue by markdebeer** [unknownskl/xbox-xcloud-client#371]
The app works beautifully when I am streaming to the Steam Deck and the display, which is hooked up to the Series X, is powered on. 

However, when the display is powered off the Steam Deck continues to receive audio but no video. I'm unsure if the Xbox can killed the video stream or what is going on. I can still connect via the official Xbox app on Android and receive the video and audio as expected.

I'm seeing this with version 1.2.0.

**Comment by unknownskl** [comment]
I think this is because the steam deck will pause the video which prevents the frames to be confirmed to the xbox. Restarting the stream should fix the problem.
It is also possible that the Xbox refuses to stream the video sometimes. Rebooting the Xbox should fix that.

**Comment by kylekaturn** [comment]
Are you using SoundBar or AV receiver?
I think this problem might related with this

https://answers.microsoft.com/en-us/xbox/forum/all/pc-to-xsx-remote-play-console-turns-on-only-see-a/eb2892ff-df7c-4c22-9775-b455f441e44a?page=3&messageId=27ec458d-3293-4247-94c5-d441455b1ccb

https://answers.microsoft.com/en-us/xbox/forum/all/xbox-series-x-remote-play-only-works-when/b6e6cd9c-7220-4c29-af7f-d579a0bc7bd9

**Comment by markdebeer** [comment]
> Are you using SoundBar or AV receiver?
> I think this problem might related with this
> 
> https://answers.microsoft.com/en-us/xbox/forum/all/pc-to-xsx-remote-play-console-turns-on-only-see-a/eb2892ff-df7c-4c22-9775-b455f441e44a?page=3&messageId=27ec458d-3293-4247-94c5-d441455b1ccb
> 
> https://answers.microsoft.com/en-us/xbox/forum/all/xbox-series-x-remote-play-only-works-when/b6e6cd9c-7220-4c29-af7f-d579a0bc7bd9
> 

Thanks! I am using a receiver so it would be the exact same issue from these articles. Sounds like an issue on Microsoft's end. Hope they fix soon!

**Comment by BinaryTweedDeej** [comment]
I'm getting this issue (black screen, but audio works) on version 1.2.0, MacOS Ventura 13.2.1, 2019 (Intel) MacBook Pro, connecting to a Series X on the same LAN.

You can see that audio packets are coming through, but absolutely nada on the video front:

<img width="320" alt="image" src="https://user-images.githubusercontent.com/1826863/220166256-8dbbcc4e-6425-405d-8ff6-9c8c804f7091.png">

Official Xbox app on iPad connected to the same network works without a problem.

Keep up the good work, I know how it is supporting open source projects :)

**Comment by mcj** [comment]
Bumping this issue, as it is still present in the 2.0.1 release.

My symptoms are pretty much the same as described in the Microsoft.com links above - if my AV receiver is powered on, then Greenlight streams my Series X video fine.  If the AV receiver is off, then there is audio but no video.  Using the Xbox iOS app works correctly in either case, so obviously MS is somehow able to work around this.
